// mario maker bingo speedrun
conditions= [
"Enemy spam",
"1-1 remake",
"No checkpoint AND no clear condition",
"Themed/Named after another game",
"Forced boss fight",
"Sound effect spam",
"Clear condition",
"Enemy spam with star",
"Dev powerup or dev route",
"Kaizo block over pit/spikes",
"Win with Yoshi",
"Forced Yoshimurder (RIP, little buddy)",
"Win as Link OR Superball Mario OR Mario 2 Mario",
"Music level",
"Cheesy goodness",
"Nonsensically-named level",
"Streamer callout in title or level",
"Tech level",
"Softlock",
"Auto level",
"Mario dies at start unless you move quickly",
"Pick a path",
"Infinite powerup bowser fight",
"On/Off blocks",
"Pun or alliteration in level title",
"Requires blind jump",
"Win with Builder suit or Hat (3D World)",
"Sniper (offscreen) Thwomps",
"Tight Speedrun",
"Autoscroller",
"Snake block",
"Skull platform",
"Spike run",
"Cheese thwarted",
"Reset door/pipe/whatever",
"True ending",
"Red coins",
"Precision level",
"Tick off a wiggler",
"Hot/Moist Garbage",
"Well-placed indicators",
"Hidden block containing enemies",
"Sing during the entire life you win on",
"Get three 1-ups",
"Get a 1-up from the flagpole or tape",
"Kill no enemies",
"Win with 0 coins",
"Multiplayer level not in multiplayer mode"
];
